// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/5ebd25423b2c3c7dc275602a40e721e994aad26d/gulp-rename/index.d.ts
declare module 'gulp-rename' {
// Type definitions for gulp-rename
// Project: https://github.com/hparra/gulp-rename
// Definitions by: Asana <https://asana.com>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference types="node"/>

namespace rename {
    interface ParsedPath {
        dirname?: string;
        basename?: string;
        extname?: string;
    }

    interface Options extends ParsedPath {
        prefix?: string;
        suffix?: string;
    }
}

function rename(name: string): NodeJS.ReadWriteStream;
function rename(callback: (path: rename.ParsedPath) => any): NodeJS.ReadWriteStream;
function rename(opts: rename.Options): NodeJS.ReadWriteStream;
export = rename;
}
